# Maximum line width
line_width: 120

# Indentation settings
tab_size: 4
use_tab_chars: false

# Put closing parentheses of multi-line statements in its own line
dangle_parens: true

# If an argument group contains more than this many sub-groups then use vertical layout
max_subgroups_hwrap: 2

# Ensure commands are consistently formatted (e.g. lowercase)
command_case: lower

# What style line endings to use in the output
line_ending: unix

# Automatically sort argument lists
autosort: true
