#!/bin/bash
# $Id$

# This utility program patches an original Philips language model file
# to use it with Sprint/Lm
#
# The following adaptations are performed:
# - Certain keywords in the class LM are changed to their non-class
#   equivalents.
# - German TeX-style umlauts are converted to UTF-8.
# - Should any non-ASCII characters occur, they are interpreted as
#   ISO-8859-1 and consequently converted to UTF-8.

if [ $# -eq 2 ]; then
    orig=$1
    out=$2
else
    echo "Usage: $0 <input> <output>"
    echo "input: original Philips language model file"
    echo "output: patched Philips LM for use with Sprint/Lm"
    exit 1
fi

echo "reading Philips language model file from $orig"
echo "writing patched LM to $out"

cat $orig \
| sed 's/"a/ä/g; s/"o/ö/g; s/"u/ü/g; s/"A/Ä/g; s/"O/Ö/g; s/"U/Ü/g; s/"s/ß/g;' \
| sed 's/VMClassMgramScore/WordMGramScore/; s/ClassList/Vocabulary/;' \
| iconv --from-code=ISO-8859-1 --to-code=UTF-8 \
> $out
