name: clang-format
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
jobs:
  compile:
    runs-on: ghcr.io/rwth-i6/rasr:build
    steps:
    - uses: actions/checkout@v2
      with:
        path: "rasr"
    - name: Compile RASR
      run: |
        cd rasr
        ./apptainer/2025-04-23_tensorflow-2.17_onnx-1.20_v2/setup_makefiles.sh
        make -j4
